# Generated by Django 4.2.30 on 2026-04-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_instructor_firstname_instructor_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='Credits',
            field=models.IntegerField(default=3),
        ),
    ]
